name: StoryChapterFrameWork

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
          cache: "maven"
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Rename build artifacts
        run: mv /home/runner/work/StoryChapterFrameWork/StoryChapterFrameWork/target/StoryChapterFrameWork-*.jar /home/runner/work/StoryChapterFrameWork/StoryChapterFrameWork/target/StoryChapterFrameWork-${{ github.run_number }}-Build.jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: MlgRushPlugin-git-${{ github.run_number }}
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/workStoryChapterFrameWork/StoryChapterFrameWork/target/StoryChapterFrameWork-*.jar
          # The desired behavior if no files are found using the provided path.

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
